import { randomUUID } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import fs from 'fs-extra';
import MarkdownIt from 'markdown-it';
import markdownItFootnote from 'markdown-it-footnote';
import { parseFragment } from 'parse5';
import YAML from 'yaml';

import {
  detectStandardFenceOpen,
  isStandardFenceClose,
  parseStandardCalloutDelimiter
} from './StandardCalloutParser.js';

export const WEB_MDBOOK_IMPLEMENTATION = 'web-mdbook-v1';
export const WEB_MDBOOK_COMPATIBILITY_VERSION = '0.5.4';
export const DEFAULT_WEB_MDBOOK_CSS = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../shared/mdbook/theme/css/itdo-mdbook.css'
);

const MARKDOWN = new MarkdownIt({
  html: true,
  linkify: false,
  typographer: false,
  maxNesting: 1024
}).use(markdownItFootnote);
const MAX_MARKDOWN_AUDIT_DEPTH = 128;
const HTML_ENTITY = /&(?:#[xX][0-9A-Fa-f]+|#\d+|[A-Za-z][A-Za-z0-9]+);?/gu;

const PUBLIC_CALLOUT_LABELS = Object.freeze({
  note: 'Note',
  tip: 'Tip',
  warning: 'Warning'
});

const MDBOOK_FILE_DIRECTIVE = /\{\{\s*#\s*(include|rustdoc_include|playground)(?=\s|\}\})/giu;
const ACTIVE_SVG_ELEMENTS = new Set([
  'animate',
  'animatemotion',
  'animatetransform',
  'audio',
  'base',
  'discard',
  'embed',
  'form',
  'foreignobject',
  'handler',
  'iframe',
  'link',
  'meta',
  'object',
  'script',
  'set',
  'style',
  'video'
]);
const SAFE_SVG_FRAGMENT_REFERENCE = /^#[A-Za-z_][A-Za-z0-9_.:-]*$/u;
const SAFE_SVG_URL_FUNCTION = /^url\(\s*#[A-Za-z_][A-Za-z0-9_.:-]*\s*\)$/iu;
const PASSIVE_WEB_ASSET_EXTENSIONS = new Set([
  '.avif',
  '.bmp',
  '.csv',
  '.gif',
  '.ico',
  '.jpeg',
  '.jpg',
  '.json',
  '.mp3',
  '.mp4',
  '.ogg',
  '.otf',
  '.png',
  '.svg',
  '.tsv',
  '.ttf',
  '.txt',
  '.wav',
  '.webm',
  '.webp',
  '.woff',
  '.woff2',
  '.yaml',
  '.yml'
]);

export class WebMdbookAdapterError extends Error {
  constructor(message) {
    super(message);
    this.name = 'WebMdbookAdapterError';
  }
}

function flattenStructure(metadata) {
  return [
    ...metadata.structure.frontmatter.map((entry) => ({ ...entry, section: 'frontmatter' })),
    ...metadata.structure.chapters.map((entry) => ({ ...entry, section: 'chapters' })),
    ...metadata.structure.backmatter.map((entry) => ({ ...entry, section: 'backmatter' }))
  ];
}

function escapeMarkdownLabel(value) {
  const source = String(value);
  const hasControl = [...source].some((character) => {
    const codePoint = character.codePointAt(0);
    return codePoint <= 0x1f || codePoint === 0x7f;
  });
  if (!source.trim() || hasControl) {
    throw new WebMdbookAdapterError('SUMMARY title must be non-empty single-line display text.');
  }
  return source
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/([\\[\]])/g, '\\$1');
}

function tomlString(value) {
  return JSON.stringify(String(value));
}

function normalizeGitHubRepositoryUrl(value) {
  const match = String(value).match(
    /^https:\/\/github\.com(?::443)?\/([^/?#]+)\/([^/?#]+?)\/?$/iu
  );
  if (!match) {
    throw new WebMdbookAdapterError(
      'web-mdbook repository.url must be a supported GitHub HTTPS repository root URL.'
    );
  }

  let owner;
  let repository;
  try {
    owner = decodeURIComponent(match[1]);
    repository = decodeURIComponent(match[2]).replace(/\.git$/u, '');
  } catch {
    throw new WebMdbookAdapterError(
      'web-mdbook repository.url contains invalid percent encoding.'
    );
  }

  const githubOwner = /^(?=.{1,39}$)[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$/u;
  const githubRepository = /^(?=.{1,100}$)[A-Za-z0-9_.-]+$/u;
  if (
    !githubOwner.test(owner) ||
    !githubRepository.test(repository) ||
    repository === '.' ||
    repository === '..'
  ) {
    throw new WebMdbookAdapterError(
      'web-mdbook repository.url must identify one GitHub owner/repository pair.'
    );
  }

  return `https://github.com/${owner}/${repository}`;
}

function createBookToml(metadata) {
  const authors = metadata.authors.map((author) => tomlString(author.name)).join(', ');
  const repositoryUrl = normalizeGitHubRepositoryUrl(metadata.repository.url);

  return [
    '# Generated by itdojp/book-formatter. Do not edit this adapter output.',
    `# Verified mdBook compatibility: ${WEB_MDBOOK_COMPATIBILITY_VERSION}`,
    '',
    '[book]',
    `title = ${tomlString(metadata.title)}`,
    `authors = [${authors}]`,
    `language = ${tomlString(metadata.language)}`,
    'src = "src"',
    '',
    '[build]',
    'build-dir = "book"',
    'create-missing = false',
    '',
    '[output.html]',
    'additional-css = ["theme/css/itdo-mdbook.css"]',
    `git-repository-url = ${tomlString(repositoryUrl)}`,
    'git-repository-icon = "fab-github"',
    ''
  ].join('\n');
}

function createSummary(entries) {
  return [
    '# Summary',
    '',
    ...entries.map((entry) =>
      `- [${escapeMarkdownLabel(entry.title)}](${entry.path.split(path.sep).join('/')})`
    ),
    ''
  ].join('\n');
}

function createSanitizedBookMetadata(metadata, edition) {
  return YAML.stringify({
    schema_version: metadata.schema_version,
    id: metadata.id,
    title: metadata.title,
    language: metadata.language,
    authors: metadata.authors.map((author) => ({ name: author.name })),
    publisher: { name: metadata.publisher.name },
    version: metadata.version,
    license: metadata.license,
    edition: {
      id: edition.id,
      title: edition.title,
      status: edition.status,
      visibility: edition.visibility
    }
  });
}

function applyVisibilityRegions(source, regions, sourcePath) {
  const normalized = String(source).replace(/\r\n?/g, '\n');
  const hadTrailingNewline = normalized.endsWith('\n');
  const lines = normalized.split('\n');
  if (hadTrailingNewline) lines.pop();
  const omitted = new Set();

  for (const region of regions) {
    if (!Number.isInteger(region.startLine) || !Number.isInteger(region.endLine)) {
      throw new WebMdbookAdapterError(
        `Invalid visibility line range in ${sourcePath}: ${region.startLine}-${region.endLine}`
      );
    }
    if (region.startLine < 1 || region.endLine < region.startLine || region.endLine > lines.length) {
      throw new WebMdbookAdapterError(
        `Visibility line range is outside ${sourcePath}: ${region.startLine}-${region.endLine}`
      );
    }

    if (region.decision === 'exclude-block') {
      for (let line = region.startLine; line <= region.endLine; line += 1) omitted.add(line);
    } else if (region.decision === 'include') {
      omitted.add(region.startLine);
      omitted.add(region.endLine);
    } else {
      throw new WebMdbookAdapterError(
        `Unsupported visibility decision in included document ${sourcePath}: ${region.decision}`
      );
    }
  }

  return lines
    .filter((_line, index) => !omitted.has(index + 1))
    .join('\n') + (hadTrailingNewline ? '\n' : '');
}

function convertPublicCallouts(source, sourcePath) {
  const normalized = String(source).replace(/\r\n?/g, '\n');
  const hadTrailingNewline = normalized.endsWith('\n');
  const lines = normalized.split('\n');
  if (hadTrailingNewline) lines.pop();
  const output = [];
  let fence = null;
  let callout = null;

  for (const line of lines) {
    if (fence) {
      output.push(callout ? (line ? `> ${line}` : '>') : line);
      if (isStandardFenceClose(line, fence)) fence = null;
      continue;
    }

    const openedFence = detectStandardFenceOpen(line);
    if (openedFence) {
      fence = openedFence;
      output.push(callout ? `> ${line}` : line);
      continue;
    }

    const delimiter = parseStandardCalloutDelimiter(line);
    if (delimiter?.kind === 'open') {
      if (!(delimiter.type in PUBLIC_CALLOUT_LABELS)) {
        throw new WebMdbookAdapterError(
          `Protected callout delimiter remained after visibility projection in ${sourcePath}: ${delimiter.type}`
        );
      }
      if (callout) {
        throw new WebMdbookAdapterError(`Nested callout is not supported in ${sourcePath}`);
      }
      callout = delimiter.type;
      output.push(`> **${PUBLIC_CALLOUT_LABELS[callout]}**`);
      output.push('>');
      continue;
    }
    if (delimiter?.kind === 'close') {
      if (!callout) {
        throw new WebMdbookAdapterError(`Orphan callout close delimiter in ${sourcePath}`);
      }
      callout = null;
      output.push('');
      continue;
    }
    if (delimiter) {
      throw new WebMdbookAdapterError(`Invalid callout delimiter in ${sourcePath}: ${line}`);
    }

    output.push(callout ? (line ? `> ${line}` : '>') : line);
  }

  if (fence) throw new WebMdbookAdapterError(`Unclosed code fence in ${sourcePath}`);
  if (callout) throw new WebMdbookAdapterError(`Unclosed callout in ${sourcePath}`);
  return output.join('\n') + (hadTrailingNewline ? '\n' : '');
}

function collectTokens(tokens) {
  const collected = [];
  for (const token of tokens) {
    collected.push(token);
    if (token.children) collected.push(...collectTokens(token.children));
  }
  return collected;
}

function maskSingleLineCodeSpans(line) {
  const characters = [...line];
  const escapedAt = (index) => {
    let backslashes = 0;
    for (let cursor = index - 1; cursor >= 0 && characters[cursor] === '\\'; cursor -= 1) {
      backslashes += 1;
    }
    return backslashes % 2 === 1;
  };

  for (let index = 0; index < characters.length; index += 1) {
    if (characters[index] !== '`' || escapedAt(index)) continue;
    let runLength = 1;
    while (characters[index + runLength] === '`') runLength += 1;
    let close = index + runLength;
    while (close < characters.length) {
      if (characters[close] !== '`') {
        close += 1;
        continue;
      }
      let closeLength = 1;
      while (characters[close + closeLength] === '`') closeLength += 1;
      if (closeLength === runLength) break;
      close += closeLength;
    }
    if (close >= characters.length) {
      index += runLength - 1;
      continue;
    }
    const end = close + runLength;
    characters.fill(' ', index, end);
    index = end - 1;
  }
  return characters.join('');
}

function decodeHtmlEntities(source) {
  return source.replace(HTML_ENTITY, (entity) => {
    const fragment = parseFragment(entity);
    const text = fragment.childNodes?.find((node) => node.nodeName === '#text')?.value;
    return text || entity;
  });
}

function destinationScheme(source) {
  const normalized = decodeHtmlEntities(source)
    .replaceAll('\t', '')
    .replaceAll('\n', '')
    .replaceAll('\r', '');
  return normalized.match(/^([A-Za-z][A-Za-z0-9+.-]*):/u)?.[1] || null;
}

function leadingBlockquotePrefix(line) {
  let cursor = 0;
  let depth = 0;
  let prefixEnd = 0;
  while (cursor < line.length) {
    while (line[cursor] === ' ' || line[cursor] === '\t') cursor += 1;
    if (line[cursor] !== '>') break;
    depth += 1;
    cursor += 1;
    prefixEnd = cursor;
  }
  while (line[prefixEnd] === ' ' || line[prefixEnd] === '\t') prefixEnd += 1;
  return { depth, content: depth ? line.slice(prefixEnd) : line };
}

function assertMarkdownAuditDepth(source, sourcePath) {
  let bracketDepth = 0;
  let maximumBracketDepth = 0;
  for (const character of source) {
    if (character === '[') {
      bracketDepth += 1;
      maximumBracketDepth = Math.max(maximumBracketDepth, bracketDepth);
    } else if (character === ']') {
      bracketDepth = Math.max(0, bracketDepth - 1);
    }
  }
  const maximumContainerDepth = Math.max(0, ...source.split('\n').map((line) => {
    const indentation = line.match(/^[ \t]*/u)?.[0] || '';
    let columns = 0;
    for (const character of indentation) {
      columns = character === '\t' ? columns + 4 - (columns % 4) : columns + 1;
    }
    const quoteDepth = leadingBlockquotePrefix(line.slice(indentation.length)).depth;
    return Math.floor(columns / 2) + quoteDepth;
  }));
  if (
    maximumBracketDepth > MAX_MARKDOWN_AUDIT_DEPTH ||
    maximumContainerDepth > MAX_MARKDOWN_AUDIT_DEPTH
  ) {
    throw new WebMdbookAdapterError(
      `Markdown link audit depth exceeds ${MAX_MARKDOWN_AUDIT_DEPTH} in ${sourcePath}`
    );
  }
}

function rejectUnsupportedSourceDestinations(source, sourcePath) {
  const normalized = String(source).replace(/\r\n?/g, '\n');
  const auditedLines = [];
  let fence = null;
  for (const line of normalized.split('\n')) {
    const containerContent = leadingBlockquotePrefix(line).content;
    if (fence) {
      if (isStandardFenceClose(containerContent, fence)) fence = null;
      continue;
    }
    const openedFence = detectStandardFenceOpen(containerContent);
    if (openedFence) {
      fence = openedFence;
      continue;
    }

    const visibleSource = maskSingleLineCodeSpans(line);
    auditedLines.push(visibleSource);
    const patterns = [
      { pattern: /(!?)\[[^\]]*\]\(\s*<?([^)>\s]+)/gu, destination: 2, image: 1 },
      {
        pattern: /^\s{0,3}\[(?:\\.|[^\x5b\x5c\x5d])+\]:\s*<?([^>\s]+)/gu,
        destination: 1,
        image: null
      }
    ];
    for (const entry of patterns) {
      for (const match of visibleSource.matchAll(entry.pattern)) {
        const scheme = destinationScheme(match[entry.destination]);
        if (!scheme) continue;
        if (scheme.toLowerCase() !== 'https') {
          const kind = entry.image && match[entry.image] === '!' ? 'image' : 'link';
          throw new WebMdbookAdapterError(
            `Unsupported external ${kind} in ${sourcePath}: ${scheme}:`
          );
        }
      }
    }
  }
  assertMarkdownAuditDepth(auditedLines.join('\n'), sourcePath);
}

function rejectMdbookFileDirectives(source, sourcePath) {
  for (const match of String(source).matchAll(MDBOOK_FILE_DIRECTIVE)) {
    const line = String(source).slice(0, match.index).split('\n').length;
    throw new WebMdbookAdapterError(
      `mdBook file directive is not allowed in ${sourcePath}:${line}: ${match[1].toLowerCase()}`
    );
  }
}

function inspectMarkdown(source, sourcePath) {
  rejectMdbookFileDirectives(source, sourcePath);
  rejectUnsupportedSourceDestinations(source, sourcePath);
  const tokens = collectTokens(MARKDOWN.parse(source, {}));
  const html = tokens.find((token) => token.type === 'html_block' || token.type === 'html_inline');
  if (html) {
    throw new WebMdbookAdapterError(
      `Reader-visible raw HTML is not supported by web-mdbook: ${sourcePath}`
    );
  }
  const destinations = [];
  for (const token of tokens) {
    if (token.type === 'link_open') {
      destinations.push({ kind: 'link', destination: token.attrGet('href') });
    } else if (token.type === 'image') {
      destinations.push({ kind: 'image', destination: token.attrGet('src') });
    }
  }
  return destinations;
}

function stripQueryAndFragment(destination) {
  const boundary = String(destination).search(/[?#]/u);
  return boundary === -1 ? String(destination) : String(destination).slice(0, boundary);
}

function decodeRelativeDestination(destination, sourcePath) {
  let decoded;
  try {
    decoded = decodeURIComponent(stripQueryAndFragment(destination));
  } catch {
    throw new WebMdbookAdapterError(`Invalid percent-encoded link in ${sourcePath}: ${destination}`);
  }
  if (!decoded || decoded.includes('\\') || decoded.includes('\0')) {
    throw new WebMdbookAdapterError(`Invalid relative link in ${sourcePath}: ${destination}`);
  }
  return decoded;
}

async function requireRegularPathBelow(bookRoot, relativePath, label) {
  const resolved = path.resolve(bookRoot, relativePath);
  const relative = path.relative(bookRoot, resolved);
  if (!relative || relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
    throw new WebMdbookAdapterError(`${label} resolves outside the book root: ${relativePath}`);
  }

  let current = bookRoot;
  for (const component of relative.split(path.sep)) {
    current = path.join(current, component);
    let stat;
    try {
      stat = await fs.lstat(current);
    } catch {
      throw new WebMdbookAdapterError(`${label} does not exist: ${relativePath}`);
    }
    if (stat.isSymbolicLink()) {
      throw new WebMdbookAdapterError(`${label} must not contain symbolic links: ${relativePath}`);
    }
  }
  const stat = await fs.lstat(resolved);
  if (!stat.isFile()) throw new WebMdbookAdapterError(`${label} must be a regular file: ${relativePath}`);
  return { resolved, relative };
}

function inspectSvgNode(node, assetPath) {
  if (node.tagName) {
    const tagName = node.tagName.toLowerCase();
    const localTagName = tagName.split(':').at(-1);
    if (ACTIVE_SVG_ELEMENTS.has(localTagName)) {
      throw new WebMdbookAdapterError(
        `SVG asset contains active element <${node.tagName}>: ${assetPath}`
      );
    }

    for (const attribute of node.attrs || []) {
      const attributeName = attribute.name.toLowerCase();
      const qualifiedName = attribute.prefix
        ? `${attribute.prefix.toLowerCase()}:${attributeName}`
        : attributeName;
      const localAttributeName = attributeName.split(':').at(-1);
      const value = attribute.value.trim();
      if (localAttributeName.startsWith('on')) {
        throw new WebMdbookAdapterError(
          `SVG asset contains event-handler attribute ${qualifiedName}: ${assetPath}`
        );
      }
      if (localAttributeName === 'style') {
        throw new WebMdbookAdapterError(
          `SVG asset contains inline style capable of external references: ${assetPath}`
        );
      }
      if (qualifiedName === 'xml:base') {
        throw new WebMdbookAdapterError(
          `SVG asset contains an alternate base URL: ${assetPath}`
        );
      }
      if (value.includes('\\')) {
        throw new WebMdbookAdapterError(
          `SVG asset contains an ambiguous escaped attribute value: ${assetPath}`
        );
      }
      if (localAttributeName === 'href' || localAttributeName === 'src') {
        if (value && !SAFE_SVG_FRAGMENT_REFERENCE.test(value)) {
          throw new WebMdbookAdapterError(
            `SVG asset contains non-local ${qualifiedName} reference: ${assetPath}`
          );
        }
      }
      if (/url\s*\(/iu.test(value) && !SAFE_SVG_URL_FUNCTION.test(value)) {
        throw new WebMdbookAdapterError(
          `SVG asset contains non-local or ambiguous CSS URL reference: ${assetPath}`
        );
      }
    }
  }

  for (const child of node.childNodes || []) inspectSvgNode(child, assetPath);
}

async function assertSafeSvgAsset(assetPath, relativePath) {
  const bytes = await fs.readFile(assetPath);
  let source;
  try {
    source = new TextDecoder('utf-8', { fatal: true }).decode(bytes);
  } catch {
    throw new WebMdbookAdapterError(`SVG asset must be valid UTF-8: ${relativePath}`);
  }
  if (/<!\s*(doctype|entity)\b|<\?xml-stylesheet\b/iu.test(source)) {
    throw new WebMdbookAdapterError(
      `SVG asset contains an external-declaration surface: ${relativePath}`
    );
  }

  const document = parseFragment(source);
  const roots = document.childNodes.filter(
    (node) => node.tagName || (node.nodeName === '#text' && node.value.trim())
  );
  if (
    roots.length !== 1 ||
    roots[0].tagName?.toLowerCase() !== 'svg' ||
    roots[0].namespaceURI !== 'http://www.w3.org/2000/svg'
  ) {
    throw new WebMdbookAdapterError(`SVG asset must contain exactly one SVG root: ${relativePath}`);
  }
  inspectSvgNode(roots[0], relativePath);
}

async function resolveDocumentAssets({
  bookRoot,
  metadata,
  sourcePath,
  destinations,
  includedDocumentPaths
}) {
  const assetRoot = path.resolve(bookRoot, metadata.source.assets);
  const assets = [];

  for (const { kind, destination } of destinations) {
    if (!destination || destination.startsWith('#')) continue;
    if (destination.startsWith('/')) {
      throw new WebMdbookAdapterError(`Root/protocol-relative ${kind} is not allowed in ${sourcePath}`);
    }

    if (/^[A-Za-z][A-Za-z0-9+.-]*:/u.test(destination)) {
      let url;
      try {
        url = new URL(destination);
      } catch {
        throw new WebMdbookAdapterError(`Invalid ${kind} URL in ${sourcePath}: ${destination}`);
      }
      if (kind === 'image' || url.protocol !== 'https:' || url.username || url.password) {
        throw new WebMdbookAdapterError(`Unsupported external ${kind} in ${sourcePath}: ${destination}`);
      }
      continue;
    }

    const decoded = decodeRelativeDestination(destination, sourcePath);
    const relative = path.normalize(path.join(path.dirname(sourcePath), decoded));
    if (relative === 'book.yaml') continue;
    if (includedDocumentPaths.has(relative)) continue;

    const { resolved, relative: verifiedRelative } = await requireRegularPathBelow(
      bookRoot,
      relative,
      `${kind} target`
    );
    const relativeToAssets = path.relative(assetRoot, resolved);
    if (
      !relativeToAssets ||
      relativeToAssets === '..' ||
      relativeToAssets.startsWith(`..${path.sep}`) ||
      path.isAbsolute(relativeToAssets)
    ) {
      throw new WebMdbookAdapterError(
        `${kind} target must be an included Markdown document, generated book.yaml, or declared asset: ${destination}`
      );
    }
    const extension = path.extname(verifiedRelative).toLowerCase();
    if (!PASSIVE_WEB_ASSET_EXTENSIONS.has(extension)) {
      throw new WebMdbookAdapterError(
        `Unsupported web asset extension ${extension || '(none)'}: ${verifiedRelative}`
      );
    }
    if (extension === '.svg') {
      await assertSafeSvgAsset(resolved, verifiedRelative);
    }
    assets.push({ source: resolved, destination: verifiedRelative });
  }

  return assets;
}

async function assertOwnedExistingOutput(outputDirectory) {
  if (!(await fs.pathExists(outputDirectory))) return;
  const stat = await fs.lstat(outputDirectory);
  if (stat.isSymbolicLink() || !stat.isDirectory()) {
    throw new WebMdbookAdapterError(`web-mdbook output must be a real directory: ${outputDirectory}`);
  }

  const manifestPath = path.join(outputDirectory, 'manifest.json');
  let manifest;
  try {
    manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'));
  } catch {
    throw new WebMdbookAdapterError(
      `Refusing to replace output without a valid adapter manifest: ${outputDirectory}`
    );
  }
  if (
    manifest.kind !== 'book-formatter.adapter-build' ||
    manifest.adapter?.target !== 'web-mdbook'
  ) {
    throw new WebMdbookAdapterError(
      `Refusing to replace output owned by another producer: ${outputDirectory}`
    );
  }
}

async function pathIdentity(candidate) {
  const stat = await fs.stat(candidate);
  return { dev: stat.dev, ino: stat.ino };
}

function samePathIdentity(left, right) {
  return left.dev === right.dev && left.ino === right.ino;
}

async function assertProtectedRootsUnchanged(protectedRoots, expectedIdentities) {
  for (const [index, protectedRoot] of protectedRoots.entries()) {
    let currentIdentity;
    try {
      currentIdentity = await pathIdentity(protectedRoot);
    } catch {
      throw new WebMdbookAdapterError(
        `Protected book path became unavailable during output replacement: ${protectedRoot}`
      );
    }
    if (!samePathIdentity(currentIdentity, expectedIdentities[index])) {
      throw new WebMdbookAdapterError(
        `Protected book path changed during output replacement: ${protectedRoot}`
      );
    }
  }
}

async function replaceOwnedDirectory({
  stagingDirectory,
  outputDirectory,
  protectedRoots,
  revalidateReplacementDirectory
}) {
  const backupDirectory = `${outputDirectory}.backup-${process.pid}-${randomUUID()}`;
  const outputExists = await fs.pathExists(outputDirectory);
  const protectedRootIdentities = await Promise.all(protectedRoots.map(pathIdentity));
  let outputMoved = false;
  let stagingInstalled = false;
  let committed = false;
  try {
    if (outputExists) {
      await fs.rename(outputDirectory, backupDirectory);
      outputMoved = true;
      await assertProtectedRootsUnchanged(protectedRoots, protectedRootIdentities);
      await revalidateReplacementDirectory(backupDirectory);
    }
    await fs.rename(stagingDirectory, outputDirectory);
    stagingInstalled = true;
    await assertProtectedRootsUnchanged(protectedRoots, protectedRootIdentities);
    if (outputMoved) await revalidateReplacementDirectory(backupDirectory);
    committed = true;
    if (outputMoved) {
      try {
        await fs.remove(backupDirectory);
      } catch (error) {
        throw new WebMdbookAdapterError(
          'New output was installed, but backup cleanup failed; retained path: ' +
            `${backupDirectory}; ${error.message}`
        );
      }
    }
  } catch (error) {
    if (committed) throw error;
    if (stagingInstalled && await fs.pathExists(outputDirectory)) {
      await fs.remove(outputDirectory);
    }
    if (outputMoved && await fs.pathExists(backupDirectory)) {
      await fs.rename(backupDirectory, outputDirectory);
    }
    throw error;
  } finally {
    await fs.remove(stagingDirectory);
  }
}

export async function writeWebMdbookProject({
  standardBook,
  edition,
  visibilityReport,
  outputDirectory,
  manifest,
  sharedCssPath,
  revalidateOutputDestination,
  revalidateReplacementDirectory,
  validateOnly = false
}) {
  if (
    typeof revalidateOutputDestination !== 'function' ||
    typeof revalidateReplacementDirectory !== 'function'
  ) {
    throw new WebMdbookAdapterError(
      'web-mdbook output replacement requires fail-closed destination revalidation callbacks.'
    );
  }

  const allEntries = flattenStructure(standardBook.metadata);
  const entryById = new Map(allEntries.map((entry) => [entry.id, entry]));
  const includedReports = visibilityReport.documents.filter(
    (document) => document.decision === 'include'
  );
  const includedEntries = includedReports.map((document) => {
    const entry = entryById.get(document.id);
    if (!entry) throw new WebMdbookAdapterError(`Missing structure entry: ${document.id}`);
    return entry;
  });
  const includedDocumentPaths = new Set(
    includedEntries.map((entry) => path.normalize(entry.path))
  );
  const convertedDocuments = [];
  const copiedAssets = new Map();

  for (const [index, entry] of includedEntries.entries()) {
    const report = includedReports[index];
    const source = await fs.readFile(path.join(standardBook.bookRoot, entry.path), 'utf8');
    const projected = applyVisibilityRegions(source, report.protectedRegions, entry.path);
    const converted = convertPublicCallouts(projected, entry.path);
    const destinations = inspectMarkdown(converted, entry.path);
    const assets = await resolveDocumentAssets({
      bookRoot: standardBook.bookRoot,
      metadata: standardBook.metadata,
      sourcePath: entry.path,
      destinations,
      includedDocumentPaths
    });
    convertedDocuments.push({ entry, converted });
    for (const asset of assets) copiedAssets.set(asset.destination, asset);
  }
  const summary = createSummary(includedEntries);
  rejectMdbookFileDirectives(summary, 'generated SUMMARY.md');
  const bookToml = createBookToml(standardBook.metadata);

  const sharedCssStat = await fs.lstat(sharedCssPath);
  if (sharedCssStat.isSymbolicLink() || !sharedCssStat.isFile()) {
    throw new WebMdbookAdapterError(`Shared mdBook CSS must be a regular file: ${sharedCssPath}`);
  }

  await assertOwnedExistingOutput(outputDirectory);
  if (validateOnly) return;

  const parent = path.dirname(outputDirectory);
  await fs.ensureDir(parent);
  const stagingDirectory = path.join(
    parent,
    `.web-mdbook-${process.pid}-${randomUUID()}.tmp`
  );

  try {
    await fs.ensureDir(path.join(stagingDirectory, 'src'));
    await fs.ensureDir(path.join(stagingDirectory, 'theme/css'));

    for (const { entry, converted } of convertedDocuments) {
      const outputPath = path.join(stagingDirectory, 'src', entry.path);
      await fs.ensureDir(path.dirname(outputPath));
      await fs.writeFile(outputPath, converted, 'utf8');
    }
    for (const asset of copiedAssets.values()) {
      const assetOutput = path.join(stagingDirectory, 'src', asset.destination);
      await fs.ensureDir(path.dirname(assetOutput));
      await fs.copyFile(asset.source, assetOutput);
    }

    await fs.writeFile(
      path.join(stagingDirectory, 'book.toml'),
      bookToml,
      'utf8'
    );
    await fs.writeFile(
      path.join(stagingDirectory, 'src/SUMMARY.md'),
      summary,
      'utf8'
    );
    await fs.writeFile(
      path.join(stagingDirectory, 'src/book.yaml'),
      createSanitizedBookMetadata(standardBook.metadata, edition),
      'utf8'
    );
    await fs.copyFile(
      sharedCssPath,
      path.join(stagingDirectory, 'theme/css/itdo-mdbook.css')
    );
    await fs.writeFile(
      path.join(stagingDirectory, 'manifest.json'),
      `${JSON.stringify(manifest, null, 2)}\n`,
      'utf8'
    );

    await revalidateOutputDestination();
    await assertOwnedExistingOutput(outputDirectory);
    const protectedRoots = [
      standardBook.bookRoot,
      standardBook.metadataPath,
      ...Object.values(standardBook.metadata.source).map(
        (relativeSource) => path.resolve(standardBook.bookRoot, relativeSource)
      )
    ];
    await replaceOwnedDirectory({
      stagingDirectory,
      outputDirectory,
      protectedRoots,
      revalidateReplacementDirectory
    });
  } catch (error) {
    await fs.remove(stagingDirectory);
    throw error;
  }
}
